"""MinIO object storage service.

Singleton client created at module import (thread-safe via urllib3 PoolManager + CPython GIL).
All I/O calls must be wrapped with asyncio.to_thread() at the call site.

Decision: minio SDK (not aioboto3) — endpoint format "localhost:9000" (no scheme)
matches config.py. Decided in CONTEXT.md Decision 1, 2026-06-11.
"""

from minio import Minio

from app.config import settings

# Singleton — created once at module import.
# Thread-safe: urllib3 PoolManager is thread-safe; _region_map dict ops protected by CPython GIL.
# Do NOT instantiate Minio inside functions — it is an expensive object with a connection pool.
_minio_client = Minio(
    endpoint=settings.minio_endpoint,
    access_key=settings.minio_access_key,
    secret_key=settings.minio_secret_key,
    secure=settings.minio_secure,
)

BUCKET_NAME = "tenderit-documents"


def ensure_bucket_exists() -> None:
    """Idempotent bucket initialization. Called from lifespan via asyncio.to_thread().

    Creates the 'tenderit-documents' bucket if it does not exist.
    Safe to call multiple times — bucket_exists check prevents double-creation.

    Security: bucket is created private (no public policy). Access only via pre-signed URLs
    generated by the backend (T-04-03 mitigation).
    """
    if not _minio_client.bucket_exists(BUCKET_NAME):
        _minio_client.make_bucket(BUCKET_NAME)
